<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/MasterPage.master" AutoEventWireup="true" CodeFile="Addcate.aspx.cs" Inherits="Admin_Addcate" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style1
    {
        width: 360px;
    }
        .style3
        {
            width: 106px;
        }
        .style4
        {
            text-align: right;
            color: Red;
            height: 30px;
            width: 106px;
        }
        .style5
        {
            width: 301px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="tbl">
    <tr>
        <td class="tblhead">
            ADD CATEGORY</td>
    </tr>
    <tr>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td>
            <table align="center" style="width: 517px">
                <tr>
                    <td class="style3">
                        &nbsp;</td>
                    <td class="style5">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="lblas">
                        Category Name :</td>
                    <td>
                        <asp:TextBox ID="txtcat" placeholder="Enter Category Name" runat="server" CssClass="txt"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                            ControlToValidate="txtcat" ErrorMessage="Please  Enter Category Name!" 
                            ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td class="style3">
                        &nbsp;</td>
                    <td class="style5">
                        <asp:Button ID="btnaddcat" runat="server" CssClass="btnadd" Text="ADD Category" 
                            onclick="btnaddcat_Click" Height="32px" Width="142px" />
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td class="style5">
                        &nbsp;<asp:GridView ID="GridView1" runat="server" 
                            AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#336666" 
                            BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
                            GridLines="Horizontal" Width="198px" AutoGenerateColumns="False" 
                            DataKeyNames="cid" onrowcancelingedit="GridView1_RowCancelingEdit" 
                            onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                            onrowupdating="GridView1_RowUpdating" >

                              <Columns>
                            <asp:CommandField CausesValidation="false" ShowEditButton="true" />
                                <asp:BoundField DataField="cname" HeaderText="CNAME" SortExpression="cname" />
                            </Columns>
                            <FooterStyle BackColor="White" ForeColor="#333333" />
                            <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="White" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F7F7F7" />
                            <SortedAscendingHeaderStyle BackColor="#487575" />
                            <SortedDescendingCellStyle BackColor="#E5E5E5" />
                            <SortedDescendingHeaderStyle BackColor="#275353" />
                        </asp:GridView>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                        &nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            &nbsp;</td>
    </tr>
</table>
</asp:Content>

